---
- name: ec2-instance
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Create key pair
      amazon.aws.ec2_key:
        name: etcd
        key_material: "{{ lookup('file', 'core.pub') }}"
        tags:
          env: demo
      register: key_pair

    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        state: running
        instance_type: t2.micro
        image_id: ami-0e58172bedd62916b # amazon linux
        count: 1
        region: eu-west-2
        network:
          assign_public_ip: true
        security_group: "{{ etcd_sg.group_name }}"
        vpc_subnet_id: "{{ etcd_subnet.subnet.id }}"
        key_name: "{{ key_pair.key.name }}"
        tags:
          env: demo

    - name: Add instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched_instances
      with_items: "{{ ec2_instance.instances }}"      
