---
- name: Create Security Group in Existing VPC
  hosts: localhost
  gather_facts: no
  vars:
    vpc_id: "your_existing_vpc_id"
    region: "eu-west-2"
    sg_name: "ansible-tech"
    your_ip_address: "your_ip_address"
    ansible_server_ip: "ansible_server_ip"
  tasks:
    - name: Create Security Group
      ec2_group:
        name: "{{ sg_name }}"
        description: "Security group for SSH and HTTP access"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ your_ip_address }}/32"
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "{{ your_ip_address }}/32"
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ ansible_server_ip }}/32"
        outbound_rules:
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0