---
- name: Provision AWS Resources
  hosts: localhost
  connection: local
  gather_facts: false

- name: include security-group file
  import_playbook: roles/securitygroup.yaml

- name: import ec2instance file
  import_playbook: roles/ec2instance.yaml
 
- name: import webserver file
  import_playbook: roles/webserver.yaml