---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        state: running
        instance_type: t2.micro
        image_id: ami-0c618421e207909d0  # Amazon Linux
        count: 1
        region: eu-west-2
        network:
          assign_public_ip: true
        security_group: "{{ etcd_sg.group_name }}"
        vpc_subnet_id: "{{ etcd_subnet.subnet.id }}"
        key_name: "my_keyy"
        tags:
          env: demo
      register: ec2_instance

    - name: Add EC2 instance to inventory
      add_host:
        hostname: "{{ ec2_instance.instances[0].public_ip_address }}"
        group: created_instances

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ ec2_instance.instances[0].public_ip_address }}"
        port: 22
        delay: 10
        timeout: 200

    # - name: Add EC2 instance to SSH known hosts
    #   known_hosts:
    #     name: "{{ ec2_instance.instances[0].public_ip_address }}"
    #     key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" # Adjust the path to your SSH public key
    #     state: present
